const recipes = [{
    delink: 'https://dagelijksekost.een.be/gerechten/chili-no-carne',
    picture: './Pictures/ChiliSinCarne.jpg',
    name: 'Chili Sin Carne',
    description: 'This flavorful dish is ideal for a quick stew on busy weeknights!',
    origin: 'Mexico',
    preparationTime: '45 min',
    difficulty: 'a',
},
{
    delink: 'https://www.indianhealthyrecipes.com/baingan-bharta/',
    picture: './Pictures/BainganBartha.jpg',
    name: 'Baingan Bhartha',
    description: 'Baingan bharta is a divine mash of smoky aubergines, mixed with Indian seasonings. Delicious for dipping with bread.',
    origin: 'India',
    preparationTime: '35 min',
    difficulty: 'bb',
},
{
    delink: 'https://www.libelle-lekker.be/bekijk-recept/18130/paprikasoep-met-mascarpone-en-pesto',
    picture: './Pictures/paprikapestomascarponesoep.jpg',
    name: 'Pepper-pesto soup',
    description: 'A rich and intensely flavoured roasted red pepper soup made with juicy and charred yellow peppers & mascarpone.',
    origin: 'Italy',
    preparationTime: '30 min',
    difficulty: 'bb',
},
{
    delink: 'https://www.feastingathome.com/vegetarian-shepherds-pie/',
    picture: './Pictures/IndianShepherdsPie.jpg',
    name: 'Indian Shepherds Pie',
    description: 'A vegetarian Shepherd\'s Pie infused with the most fragrant Indian spices.',
    origin: 'India',
    preparationTime: '1h15 min',
    difficulty: 'ccc',
},
{
    delink: 'https://www.leukerecepten.nl/recepten/shakshuka/',
    picture: './Pictures/Shakshuka.jpg',
    name: 'Shakshuka',
    description: 'Shakshuka is a North African and Middle Eastern meal of poached eggs in a simmering tomato sauce with spices.',
    origin: 'Tunisia',
    preparationTime: '35 min',
    difficulty: 'a',
},
{
    delink: 'https://www.veguru.be/recipe/vegan-stoverij/',
    picture: './Pictures/vegan-stew.jpg',
    name: 'Vegan Stew',
    description: 'A delicious stew with fries always tastes great! This Flemish classic is easy to make without meat.',
    origin: 'Belgium',
    preparationTime: '2h15 min',
    difficulty: 'ccc',
},
{
    delink: 'https://cookieandkate.com/thai-panang-curry-recipe/',
    picture: './Pictures/PanaengCurry.jpg',
    name: 'Penaeng curry',
    description: 'It\'s rich and spicy with a distinctly unique flavor from the addition of kaffir lime leaves and panaeng curry paste.',
    origin: 'Thailand',
    preparationTime: '45 min',
    difficulty: 'a',
},
{
    delink: 'https://www.healthyfood.com/healthy-recipes/vegetarian-tagine/',
    picture: './Pictures/Tagine.jpg',
    name: 'Vegetarian Tagine',
    description: 'This full-flavoured tagine is a cheap, healthy way of getting extra vegetables into your family\'s diet. ',
    origin: 'Morocco',
    preparationTime: '1h10 min',
    difficulty: 'bb',
},
{
    delink: 'https://chickslovefood.com/recept/pad-thai-met-tofu/',
    picture: './Pictures/PadThai.jpg',
    name: 'Pad Thai',
    description: 'A stir-fried rice noodle dish commonly served as a street food in Thailand as part of the country\'s cuisine.',
    origin: 'Thailand',
    preparationTime: '25 min',
    difficulty: 'a',
},
{
    delink: 'https://www.mygingergarlickitchen.com/jaipuri-aloo-pyaaz-ki-sabzi-potato-onion-curry-video-recipe/',
    picture: './Pictures/JaipuriAloo.jpg',
    name: 'Jaipuri Aloo',
    description: 'A heavenly preparation using potatoes and onions, cooked in a scrumptious curry, packed with savoury flavors',
    origin: 'India',
    preparationTime: '45 min',
    difficulty: 'bb',
},
{
    delink: 'https://www.hellofresh.be/recipes/linguine-met-cherrytomaten-uit-de-oven-5be18ffeae08b5275a1375f2',
    picture: './Pictures/LinguineCherrytomaten.jpg',
    name: 'Cherrytom. Linguine',
    description: 'Juicy cherry tomatoes that burst open in warm olive oil, creating a luxurious sauce that comes together in  minutes.',
    origin: 'Italy',
    preparationTime: '30 min',
    difficulty: 'a',
},
{
    delink: 'https://www.libelle-lekker.be/bekijk-recept/84072/veganistische-vol-au-vent-1',
    picture: './Pictures/vol-au-vegan.jpg',
    name: 'Vol-Au-Vegan',
    description: 'An extremely delicious vegan version of the classic vol-au-vent.',
    origin: 'Belgium',
    preparationTime: '45 min',
    difficulty: 'bb',
},
{
    delink: 'https://www.hellofresh.be/recipes/groentepaella-met-krokante-halloumi-5f0c61f1c3795f61c21f5d47',
    picture: './Pictures/paella.jpg',
    name: 'Vegetable Paella',
    description: 'This vegetable paella with crispy halloumi is ideal for the lovers of Spanish food.',
    origin: 'Spain',
    preparationTime: '30 min',
    difficulty: 'bb',
},
{
    delink: 'https://lekkertafelen.nl/recepten/saus/jachtsaus/',
    picture: './Pictures/jachtsaus.jpg',
    name: 'Jachtsaus',
    description: 'A divine culinary creation that adds a touch of enchantment to any meal.',
    origin: 'Belgium',
    preparationTime: '15 min',
    difficulty: 'a',
},
]

export {
    recipes
};